[package]
name = "trading-rs"
version = "0.1.0"
authors = ["Emirhan Taşdeviren <emirhan.tasdeviren@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
chrono = "0.4"
sha2 = "0.9"
hmac = "0.10"
